spring:
  datasource:
    username: FonumKasutajaRene
    password: FonumKasutajaRene
    url: jdbc:mysql://localhost:3306/fonum_andmebaas
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect